---
- name: Test API Connection
  hosts: localhost
  tasks:
    - name: Test API Connection
      fog_ansible:
        url: "{{ fog_url }}"
        fog_api_token: "{{ fog_api_token }}"
        fog_user_token: "{{ fog_user_token }}"
        action: "list_hosts"
        output: "full"
      register: api_connection_result

    - name: Debug API Connection Result
      ansible.builtin.debug:
        var: api_connection_result