---
- hosts: localhost
  tasks:
    - name: Test API Connection
      fog_ansible:
        url: "{{ fog_url }}"
        fog_api_token: "{{ fog_api_token }}"
        fog_user_token: "{{ fog_user_token }}"
        action: "list_hosts"
        output: "full"
      register: api_connection_result

    - debug:
        var: api_connection_result